server.port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/medisoft

logging.pattern.console: '%d{yy-MM-dd HH:mm:ss} request=%X{REQUEST_ID} %-5level %logger{36} %msg%n'
logging.level.root: INFO

nzis:
  api-url: https://ptest-api.his.bg
  auth-url: https://ptest-auth.his.bg
