CREATE TABLE PATIENT (
    ID SERIAL PRIMARY KEY,
    FNAME VARCHAR(30),
    MNAME VARCHAR(30),
    LNAME VARCHAR(30),
    BIRTHDATE DATE,
    EMAIL VARCHAR(40),
    GENDER CHAR(1),
    NATIONALITY VARCHAR(30),
    PHONE VARCHAR(30),
    ACTIVE BIT,
    SOCIAL_GROUP VARCHAR(30),
    MARITAL_STATUS VARCHAR(30),
    ADDRESS_ID NUMBER,
    CONTACT_PERSON_ID NUMBER,
    GENERAL_PRACTITIONER VARCHAR(40),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
    FOREIGN KEY (CONTACT_PERSON_ID) REFERENCES CONTACT_PERSON(CONTACT_PERSON_ID)
);

CREATE TABLE ADDRESS(
    ADDRESS_ID NUMBER,
    CITY VARCHAR(30),
    COUNTRY VARCHAR(30),
    COUNTY VARCHAR(30),
    LINE VARCHAR(30),
    POSTAL_CODE VARCHAR(30)
);

CREATE TABLE CONTACT_PERSON(
    CONTACT_PERSON_ID NUMBER,
    RELATIONSHIP VARCHAR(50),
    FNAME VARCHAR(30),
    MNAME VARCHAR(30),
    LNAME VARCHAR(30),
    EMAIL VARCHAR(40),
    GENDER CHAR(1),
    NATIONALITY VARCHAR(30),
    PHONE VARCHAR(30),
    ADDRESS_ID NUMBER,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);
