CREATE TABLE ADDRESS
(
    ID          SERIAL PRIMARY KEY,
    CITY        VARCHAR(30),
    COUNTRY     VARCHAR(30),
    COUNTY      VARCHAR(30),
    LINE        VARCHAR(30),
    POSTAL_CODE VARCHAR(30)
);

CREATE TABLE CONTACT_PERSON
(
    ID           SERIAL PRIMARY KEY,
    RELATIONSHIP VARCHAR(50),
    F_NAME       VARCHAR(25),
    M_NAME       VARCHAR(30),
    L_NAME       VARCHAR(30),
    EMAIL        VARCHAR(40),
    GENDER       CHAR(1),
    NATIONALITY  VARCHAR(30),
    PHONE        VARCHAR(30),
    ADDRESS_ID   INT,
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
);

CREATE TABLE PATIENT
(
    ID                   SERIAL PRIMARY KEY,
    EGN                  VARCHAR(20),
    F_NAME               VARCHAR(30),
    M_NAME               VARCHAR(30),
    L_NAME               VARCHAR(30),
    BIRTHDATE            DATE,
    EMAIL                VARCHAR(40),
    GENDER               CHAR(1),
    NATIONALITY          VARCHAR(30),
    PHONE                VARCHAR(30),
    ACTIVE               BOOLEAN,
    SOCIAL_GROUP         VARCHAR(30),
    MARITAL_STATUS       VARCHAR(30),
    ADDRESS_ID           INT,
    CONTACT_PERSON_ID    INT,
    GENERAL_PRACTITIONER VARCHAR(40),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID),
    FOREIGN KEY (CONTACT_PERSON_ID) REFERENCES CONTACT_PERSON (ID)
);
